version: '3.8'
services:
    go-app: 
        container_name: go-app
        image: go-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html/
        ports:
            - 8089:8081